package com.obrit.android.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.obrit.obrit.shared.designsystem.tokens.atom.color.AtomColors
import com.obrit.obrit.shared.designsystem.tokens.semantic.SemanticColors

val LocalOBRitColor =
    staticCompositionLocalOf {
        OBRitColor()
    }

@Immutable
data class OBRitColor(
    val common00: Color = Color(AtomColors.Common.S00),
    val common100: Color = Color(AtomColors.Common.S100),
    val backgroundDefaultDimDefault: Color = Color(SemanticColors.Background.Default.DimDefault),
    val gray50: Color = Color(AtomColors.Gray.S50),
    val gray100: Color = Color(AtomColors.Gray.S100),
    val gray150: Color = Color(AtomColors.Gray.S150),
    val gray200: Color = Color(AtomColors.Gray.S200),
    val gray250: Color = Color(AtomColors.Gray.S250),
    val gray300: Color = Color(AtomColors.Gray.S300),
    val gray400: Color = Color(AtomColors.Gray.S400),
    val gray450: Color = Color(AtomColors.Gray.S450),
    val gray500: Color = Color(AtomColors.Gray.S500),
    val gray600: Color = Color(AtomColors.Gray.S600),
    val gray700: Color = Color(AtomColors.Gray.S700),
    val gray750: Color = Color(AtomColors.Gray.S750),
    val gray800: Color = Color(AtomColors.Gray.S800),
    val gray850: Color = Color(AtomColors.Gray.S850),
    val gray900: Color = Color(AtomColors.Gray.S900),
    val green50: Color = Color(AtomColors.Green.S50),
    val green100: Color = Color(AtomColors.Green.S100),
    val green150: Color = Color(AtomColors.Green.S150),
    val green200: Color = Color(AtomColors.Green.S200),
    val green250: Color = Color(AtomColors.Green.S250),
    val green300: Color = Color(AtomColors.Green.S300),
    val green400: Color = Color(AtomColors.Green.S400),
    val green450: Color = Color(AtomColors.Green.S450),
    val green500: Color = Color(AtomColors.Green.S500),
    val green600: Color = Color(AtomColors.Green.S600),
    val green700: Color = Color(AtomColors.Green.S700),
    val green750: Color = Color(AtomColors.Green.S750),
    val green800: Color = Color(AtomColors.Green.S800),
    val green850: Color = Color(AtomColors.Green.S850),
    val green900: Color = Color(AtomColors.Green.S900),
    val red50: Color = Color(AtomColors.Red.S50),
    val red100: Color = Color(AtomColors.Red.S100),
    val red150: Color = Color(AtomColors.Red.S150),
    val red200: Color = Color(AtomColors.Red.S200),
    val red250: Color = Color(AtomColors.Red.S250),
    val red300: Color = Color(AtomColors.Red.S300),
    val red400: Color = Color(AtomColors.Red.S400),
    val red450: Color = Color(AtomColors.Red.S450),
    val red500: Color = Color(AtomColors.Red.S500),
    val red600: Color = Color(AtomColors.Red.S600),
    val red700: Color = Color(AtomColors.Red.S700),
    val red750: Color = Color(AtomColors.Red.S750),
    val red800: Color = Color(AtomColors.Red.S800),
    val red850: Color = Color(AtomColors.Red.S850),
    val red900: Color = Color(AtomColors.Red.S900),
    val yellow50: Color = Color(AtomColors.Yellow.S50),
    val yellow100: Color = Color(AtomColors.Yellow.S100),
    val yellow150: Color = Color(AtomColors.Yellow.S150),
    val yellow200: Color = Color(AtomColors.Yellow.S200),
    val yellow250: Color = Color(AtomColors.Yellow.S250),
    val yellow300: Color = Color(AtomColors.Yellow.S300),
    val yellow400: Color = Color(AtomColors.Yellow.S400),
    val yellow450: Color = Color(AtomColors.Yellow.S450),
    val yellow500: Color = Color(AtomColors.Yellow.S500),
    val yellow600: Color = Color(AtomColors.Yellow.S600),
    val yellow700: Color = Color(AtomColors.Yellow.S700),
    val yellow750: Color = Color(AtomColors.Yellow.S750),
    val yellow800: Color = Color(AtomColors.Yellow.S800),
    val yellow850: Color = Color(AtomColors.Yellow.S850),
    val yellow900: Color = Color(AtomColors.Yellow.S900),
    val blue50: Color = Color(AtomColors.Blue.S50),
    val blue100: Color = Color(AtomColors.Blue.S100),
    val blue150: Color = Color(AtomColors.Blue.S150),
    val blue200: Color = Color(AtomColors.Blue.S200),
    val blue250: Color = Color(AtomColors.Blue.S250),
    val blue300: Color = Color(AtomColors.Blue.S300),
    val blue400: Color = Color(AtomColors.Blue.S400),
    val blue450: Color = Color(AtomColors.Blue.S450),
    val blue500: Color = Color(AtomColors.Blue.S500),
    val blue600: Color = Color(AtomColors.Blue.S600),
    val blue700: Color = Color(AtomColors.Blue.S700),
    val blue750: Color = Color(AtomColors.Blue.S750),
    val blue800: Color = Color(AtomColors.Blue.S800),
    val blue850: Color = Color(AtomColors.Blue.S850),
    val blue900: Color = Color(AtomColors.Blue.S900),
)
