import SwiftUI

// Generated by ./gradlew generateIosDesignTokens from shared/design-system tokens.
// Do not edit token values directly; update the Kotlin token source instead.

public enum OBRitColors {
    public static let common00 = color(0xFFFFFFFF)
    public static let common100 = color(0xFF101213)
    public static let commonBlack00_80 = color(0xCC000000)
    public static let commonBlack00_60 = color(0x99000000)
    public static let commonBlack00_40 = color(0x66000000)
    public static let commonBlack00_20 = color(0x33000000)
    public static let commonWhite00_80 = color(0xCCFFFFFF)
    public static let commonWhite00_60 = color(0x99FFFFFF)
    public static let commonWhite00_40 = color(0x66FFFFFF)
    public static let commonWhite00_20 = color(0x33FFFFFF)
    public static let backgroundDefaultDimDefault = color(0xCC000000)
    public static let gray50 = color(0xFFF5F5F5)
    public static let gray100 = color(0xFFE6E7E9)
    public static let gray150 = color(0xFFD7D9DB)
    public static let gray200 = color(0xFFCBCCCF)
    public static let gray250 = color(0xFFBFC0C2)
    public static let gray300 = color(0xFFB2B3B4)
    public static let gray400 = color(0xFFA1A2A3)
    public static let gray450 = color(0xFF888A8E)
    public static let gray500 = color(0xFF76777A)
    public static let gray600 = color(0xFF67696B)
    public static let gray700 = color(0xFF515355)
    public static let gray750 = color(0xFF393A3D)
    public static let gray800 = color(0xFF2E2F33)
    public static let gray850 = color(0xFF24242A)
    public static let gray900 = color(0xFF1D1B20)
    public static let grayOpacity700 = color(0xB2515355)
    public static let grayOpacity750 = color(0xB2393A3D)
    public static let grayOpacity800 = color(0xB22E2F33)
    public static let grayOpacity850 = color(0xB224242A)
    public static let grayOpacity900 = color(0xB21D1B20)
    public static let green50 = color(0xFFD3FCF5)
    public static let green100 = color(0xFFBEFBF0)
    public static let green150 = color(0xFF92F7E6)
    public static let green200 = color(0xFF7CF5E1)
    public static let green250 = color(0xFF67F4DC)
    public static let red100 = color(0xFFFFCDBD)
    public static let red250 = color(0xFFFF7A4E)
    public static let green300 = color(0xFF25EFCD)
    public static let green400 = color(0xFF24DABB)
    public static let green450 = color(0xFF23BAA2)
    public static let green500 = color(0xFF22A490)
    public static let green600 = color(0xFF218F7F)
    public static let green700 = color(0xFF217B6E)
    public static let green750 = color(0xFF20665D)
    public static let green800 = color(0xFF1F504B)
    public static let green850 = color(0xFF1F3B3A)
    public static let green900 = color(0xFF1E2628)
    public static let red50 = color(0xFFFFDED3)
    public static let red150 = color(0xFFFFBDA6)
    public static let red200 = color(0xFFFF9B7A)
    public static let red300 = color(0xFFFF5922)
    public static let red400 = color(0xFFE85321)
    public static let red450 = color(0xFFD24D21)
    public static let red500 = color(0xFFBB4621)
    public static let red600 = color(0xFFA54021)
    public static let red700 = color(0xFF8E3A21)
    public static let red750 = color(0xFF773421)
    public static let red800 = color(0xFF612E20)
    public static let red850 = color(0xFF4A2720)
    public static let red900 = color(0xFF342120)
    public static let yellow50 = color(0xFFFFF5CC)
    public static let yellow100 = color(0xFFFFF0B2)
    public static let yellow150 = color(0xFFFFEB99)
    public static let yellow200 = color(0xFFFFE066)
    public static let yellow250 = color(0xFFFFD633)
    public static let yellow300 = color(0xFFFFCC00)
    public static let yellow400 = color(0xFFE8BA03)
    public static let yellow450 = color(0xFFD2A906)
    public static let yellow500 = color(0xFFBB970A)
    public static let yellow600 = color(0xFFA5850D)
    public static let yellow700 = color(0xFF8E7410)
    public static let yellow750 = color(0xFF776213)
    public static let yellow800 = color(0xFF615016)
    public static let yellow850 = color(0xFF4A3E1A)
    public static let yellow900 = color(0xFF342D1D)
    public static let blue50 = color(0xFFCCE7FF)
    public static let blue100 = color(0xFFB2DBFF)
    public static let blue150 = color(0xFF99CFFF)
    public static let blue200 = color(0xFF66B8FF)
    public static let blue250 = color(0xFF33A0FF)
    public static let blue300 = color(0xFF0088FF)
    public static let blue400 = color(0xFF037DE9)
    public static let blue450 = color(0xFF0672D2)
    public static let blue500 = color(0xFF0967BC)
    public static let blue600 = color(0xFF0C5CA6)
    public static let blue700 = color(0xFF0F528F)
    public static let blue750 = color(0xFF114779)
    public static let blue800 = color(0xFF143C63)
    public static let blue850 = color(0xFF17314D)
    public static let blue900 = color(0xFF1A2636)
    public static let backgroundDefaultDefault = color(0xFF1D1B20)
    public static let backgroundDefaultDefaultHover = color(0xFF2E2F33)
    public static let backgroundDefaultSecondary = color(0xFF24242A)
    public static let backgroundDefaultSecondaryHover = color(0xFF1D1B20)
    public static let backgroundDefaultTertiary = color(0xFF393A3D)
    public static let backgroundDefaultLightGrayDefault = color(0xFFF5F5F5)
    public static let backgroundDefaultLightGraySecondary = color(0xFFE6E7E9)
    public static let backgroundDefaultLightGrayTertiary = color(0xFFBFC0C2)
    public static let backgroundDefaultMiddleGrayDefault = color(0xFF888A8E)
    public static let backgroundDefaultMiddleGraySecondary = color(0xFF67696B)
    public static let backgroundDefaultMiddleGrayTertiary = color(0xFF515355)
    public static let backgroundDefaultDimSecondary = color(0xB22E2F33)
    public static let backgroundDefaultDimTertiary = color(0xB2515355)
    public static let backgroundWarningDefault = color(0xFFFF5922)
    public static let backgroundWarningHover = color(0xFFD24D21)
    public static let backgroundWarningSecondary = color(0xFFBB4621)
    public static let backgroundWarningSecondaryHover = color(0xFFA54021)
    public static let backgroundPositiveDefault = color(0xFF25EFCD)
    public static let backgroundPositiveHover = color(0xFF24DABB)
    public static let backgroundPositiveSecondary = color(0xFF23BAA2)
    public static let backgroundPositiveSecondaryHover = color(0xFF22A490)
    public static let backgroundDisabledDefault = color(0xFF515355)
    public static let textDefaultDefault = color(0xFFFFFFFF)
    public static let textDefaultSecondary = color(0xFFB2B3B4)
    public static let textDefaultTertiary = color(0xFF76777A)
    public static let textDefaultDarkDefault = color(0xFF1D1B20)
    public static let textDefaultDarkSecondary = color(0xFF393A3D)
    public static let textDefaultDarkTertiary = color(0xFF67696B)
    public static let textWarningDefault = color(0xFFFF5922)
    public static let textWarningSecondary = color(0xFFE85321)
    public static let textWarningTertiary = color(0xFFD24D21)
    public static let textPositiveDefault = color(0xFF25EFCD)
    public static let textPositiveSecondary = color(0xFF24DABB)
    public static let textPositiveTertiary = color(0xFF23BAA2)
    public static let textDisabledDefault = color(0xFF515355)
    public static let textDisabledOnDisabled = color(0xFFBFC0C2)
    public static let borderDefaultDefault = color(0xFF393A3D)
    public static let borderDefaultSecondary = color(0xFF67696B)
    public static let borderDefaultTertiary = color(0xFF888A8E)
    public static let borderWarningDefault = color(0xFFFF5922)
    public static let borderWarningSecondary = color(0xFFE85321)
    public static let borderWarningTertiary = color(0xFFD24D21)
    public static let borderPositiveDefault = color(0xFF25EFCD)
    public static let borderPositiveSecondary = color(0xFF24DABB)
    public static let borderPositiveTertiary = color(0xFF23BAA2)
    public static let borderDisabledDefault = color(0xFF515355)
    public static let iconDefaultDefault = color(0xFFFFFFFF)
    public static let iconDefaultSecondary = color(0xFFF5F5F5)
    public static let iconDefaultTertiary = color(0xFFE6E7E9)
    public static let iconWarningDefault = color(0xFFFF5922)
    public static let iconWarningSecondary = color(0xFFE85321)
    public static let iconWarningTertiary = color(0xFFD24D21)
    public static let iconPositiveDefault = color(0xFF25EFCD)
    public static let iconPositiveSecondary = color(0xFF24DABB)
    public static let iconPositiveTertiary = color(0xFF23BAA2)
    public static let iconDisabledDefault = color(0xFF67696B)
    public static let iconDisabledOnDisabled = color(0xFFBFC0C2)
    public static let surfaceDefaultDefaultDark = color(0xFF2E2F33)
    public static let surfaceDefaultDefaultLight = color(0xFFFFFFFF)
    public static let surfaceDefaultDefaultHoverLight = color(0x66FFFFFF)

    public static func color(_ argb: Int64) -> Color {
        let value = UInt64(bitPattern: argb)
        let alpha = Double((value >> 24) & 0xFF) / 255.0
        let red = Double((value >> 16) & 0xFF) / 255.0
        let green = Double((value >> 8) & 0xFF) / 255.0
        let blue = Double(value & 0xFF) / 255.0
        return Color(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }
}

public enum OBRitSpacing {
    public static let s0: CGFloat = 0
    public static let px: CGFloat = 1
    public static let s0_5: CGFloat = 2
    public static let s1: CGFloat = 4
    public static let s1_5: CGFloat = 6
    public static let s2: CGFloat = 8
    public static let s2_5: CGFloat = 10
    public static let s3: CGFloat = 12
    public static let s4: CGFloat = 16
    public static let s5: CGFloat = 20
    public static let s6: CGFloat = 24
    public static let s7: CGFloat = 28
    public static let s8: CGFloat = 32
    public static let s9: CGFloat = 36
    public static let s10: CGFloat = 40
    public static let s11: CGFloat = 44
    public static let s12: CGFloat = 48
    public static let s14: CGFloat = 56
    public static let s16: CGFloat = 64
    public static let s20: CGFloat = 80
    public static let s24: CGFloat = 96
    public static let s28: CGFloat = 112
    public static let s32: CGFloat = 128
    public static let s36: CGFloat = 144
    public static let s40: CGFloat = 160
}

public enum OBRitRadius {
    public static let extraSmall: CGFloat = 4
    public static let small: CGFloat = 8
    public static let middle: CGFloat = 10
    public static let large: CGFloat = 12
    public static let extraLarge: CGFloat = 16
    public static let bottomSheet: CGFloat = 28
    public static let exception: CGFloat = 1000
}

public enum OBRitFontFamily {
    public static let fontSans = "Pretendard"
}

public enum OBRitFontWeight {
    public static let regular: Int32 = 400
    public static let medium: Int32 = 500
    public static let semiBold: Int32 = 600
    public static let bold: Int32 = 700
}

public enum OBRitTypography {
    public struct TextToken {
        public let size: CGFloat
        public let lineHeight: CGFloat
    }

    private static let letterSpacingPercent: CGFloat = -3

    public static let s2xs = TextToken(size: 10, lineHeight: 16)
    public static let xs = TextToken(size: 12, lineHeight: 18)
    public static let small = TextToken(size: 13, lineHeight: 20)
    public static let base = TextToken(size: 14, lineHeight: 22)
    public static let lg = TextToken(size: 15, lineHeight: 24)
    public static let xl = TextToken(size: 16, lineHeight: 24)
    public static let s2xl = TextToken(size: 18, lineHeight: 24)
    public static let s3xl = TextToken(size: 20, lineHeight: 30)
    public static let s4xl = TextToken(size: 22, lineHeight: 32)
    public static let s5xl = TextToken(size: 24, lineHeight: 36)
    public static let s6xl = TextToken(size: 28, lineHeight: 40)
    public static let s7xl = TextToken(size: 32, lineHeight: 44)
    public static let s = small

    public static func font(_ token: TextToken, weight: Int32 = OBRitFontWeight.regular) -> Font {
        Font.custom(fontName(for: weight), size: token.size)
    }

    public static func fontName(for weight: Int32) -> String {
        switch weight {
        case OBRitFontWeight.bold:
            return "Pretendard-Bold"
        case OBRitFontWeight.semiBold:
            return "Pretendard-SemiBold"
        case OBRitFontWeight.medium:
            return "Pretendard-Medium"
        default:
            return "Pretendard-Regular"
        }
    }

    public static func letterSpacing(for token: TextToken) -> CGFloat {
        token.size * letterSpacingPercent / 100
    }
}

public enum OBRitEffects {
    public static let backgroundBlur0: CGFloat = 0
    public static let backgroundBlur4: CGFloat = 4
    public static let backgroundBlur8: CGFloat = 8
    public static let backgroundBlur12: CGFloat = 12
    public static let backgroundBlur16: CGFloat = 16
}

public struct OBRitTextStyle: ViewModifier {
    let token: OBRitTypography.TextToken
    let weight: Int32
    let color: Color

    public func body(content: Content) -> some View {
        content
            .font(OBRitTypography.font(token, weight: weight))
            .tracking(OBRitTypography.letterSpacing(for: token))
            .lineSpacing(max(0, token.lineHeight - token.size))
            .foregroundStyle(color)
    }
}

public extension View {
    func obritTextStyle(
        _ token: OBRitTypography.TextToken,
        weight: Int32 = OBRitFontWeight.regular,
        color: Color
    ) -> some View {
        modifier(OBRitTextStyle(token: token, weight: weight, color: color))
    }
}
